account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('book_login/', views.book_login, name='login'),
    path('book_register/', views.book_register, name='register'),
    path('book_logout/', views.book_logout, name='logout')
]

eBooking/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include("booking.urls")), #หน้าใช้งานที่เป็น user
    path('account/', include("account.urls")) #หน้า login/register
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    name = models.CharField(max_length=100)
    open_time = models.TimeField()
    close_time = models.TimeField()
    capacity = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Booking(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField(null=True)
    description = models.TextField()
    status = models.CharField(null=True, default=None, choices=(
        ("รออนุมัติ", "Unknow"),
        ("ไม่อนุมัติ", "No"),
        ("อนุมัติ", "Yes")
    ), max_length=100)
    status_remark = models.TextField(null=True, blank=True)
    book_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    book_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.room.name

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}" />
    <link rel="stylesheet" href="{% static 'css/gijgo.min.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Mitr|Prompt&display=swap&subset=thai" rel="stylesheet">
</head>
    <style>
        nav{
            font-weight: bold;
        }
        body{
            font-family: 'Prompt', sans-serif;
        }
    </style>
    <title>e-Booking</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="\">E-BOOKING</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    {% if perms.booking.view_booking %}
                    <li class="nav-item">
                        <a class="nav-link" href="/book_list/">ข้อมูลการจอง</a>
                    </li>
                    {% endif %}
                    {% if perms.booking.change_booking %}
                    <li class="nav-item">
                        <a class="nav-link" href="/">รายการที่ร้องขอ</a>
                    </li>
                    {% endif %}
                    {% if perms.booking.change_room %}
                    <li class="nav-item">
                        <a class="nav-link" href="/room_list/">จัดการสถานที่</a>
                    </li>
                    {% endif %}
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item"><span class="navbar-brand">Hello, {{ user.username }}</span></li>
                    <li class="nav-item"><span class="navbar-brand"></span></li>
                    <li class="nav-item"><a href="/account/book_logout/" class="nav-link bg-light text-dark border rounded">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a href="/account/book_register/" class="nav-link bg-light text-dark border rounded">Sign up</a></li>
                    <li class="nav-item"><span class="navbar-brand text-dark"></span></li>
                    <li class="nav-item"><a href="/account/book_login/" class="nav-link">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% if error %}
    <div class="alert alert-danger alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ error }}
    </div>
    {% endif %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/gijgo.min.js' %}" type="text/javascript"></script>
    {% block content %}
    {% endblock content %}
    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4',
        });
        $('#timepicker1').timepicker({
            uiLibrary: 'bootstrap',
            language: 'en',
        });
        $('#timepicker2').timepicker({
            uiLibrary: 'bootstrap',
            language: 'en',
        });
        function alert_cofrim(text) {
            let result = confirm(text);
            if (result){
                return true;
            }
            else{
                return false;
            }
        }
        $(document).ready(function () {
            $('#dtBasicExample').DataTable({
                "pagingType": "simple" // "simple" option for 'Previous' and 'Next' buttons only
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
</body>
</html>